Tasks completed
Cumsterdump/itc-frontend pull request #1
Opened 2018-03-04 14:30 UTC by Cumsterdump

2018-03-10 16:47 UTC, mlshv commented
Имя папки не по-православному
http://telegra.ph/Kak-sdavat-domashku-03-10

2018-03-10 16:58 UTC, mlshv requested changes
орнул с примеров gitIn

2018-03-10 16:58 UTC, mlshv commented on 000/index.html
> +          a.push(b[i]);
ай вэй
ненене
используй concat, а ещё лучше spread operator

2018-03-10 16:58 UTC, mlshv commented on 000/index.html
> +          multipliers.push(arguments[i]);
используй rest operator

2018-03-10 16:58 UTC, mlshv commented on 000/index.html
> +        return multipliers.reduce(function(previous, current, index, array) {
два последних аргумента не используются, их можно не писать

и ещё лучше заюзать стрелочную функцию

2018-03-10 16:58 UTC, mlshv commented on 000/index.html
> +        return encodeURI(query);
у тебя в конце строки всегда амперсанд висячий получается, обрешь его

2018-03-17 10:44 UTC, Cumsterdump commented
Всё поправил, в процессе заюзав гит. Не всё так сложно с ним, оказывается.

2018-03-17 10:48 UTC, Cumsterdump commented on homework0/index.html
> +      function mergeArrays(a, b) {
Оно же так делается? Или я опять накосячил?

2018-03-17 10:48 UTC, Cumsterdump commented on homework0/index.html
> +
Сейчас норм?

2018-03-17 10:49 UTC, Cumsterdump commented on homework0/index.html
> +
Заодно понял, что такое spread и rest.

2018-03-17 10:49 UTC, Cumsterdump commented on homework0/index.html
> +
Ну, в общем-то, вот.

2018-03-17 10:51 UTC, Cumsterdump commented on homework0/index.html
> +
Тут у нас spread...

2018-03-17 10:52 UTC, Cumsterdump commented on homework0/index.html
> +
...а тут rest. Заодно разобрался, в чём разница.

2018-03-18 08:46 UTC, merged